# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Weather
  #pod 'SVProgressHUD', '~> 2.2'

  target 'iOS WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS WeatherUITests' do
    # Pods for testing
  end

end
